#!/bin/bash

set -e

echo "[1/4]: Building Code"
scripts/build

echo "[2/4]: Linting Code"
scripts/lint

echo "[3/4]: Testing Project"
scripts/test

echo "[4/4]: Publishing to NPM"
npm version patch
npm publish

echo ""
echo "CI completed succesfully 🎉"
echo ""
